### ISSUE TITLE
ALBert比bert慢？

### ISSUE THREAD

**Issue by lshowway** [lonePatient/albert_pytorch#13]
albert xlarge, share_type=all的时候，参数量比bert小。按理说，是不是应该比BERT的fine-tune的更快？（在相同数据集的情况下）
为什么我这边albert 无论large还是xlarge比bert慢好多呢？

**Comment by lonePatient** [comment]
@lshowway  albert通过共享以及project layer大大减小了参数量，但是每一层该算的还是要算的，large和xlarge来看，显存能装下，但是其实每一层计算增加了。

**Comment by lshowway** [comment]
> @lshowway albert通过共享以及project layer大大减小了参数量，但是每一层该算的还是要算的，large和xlarge来看，显存能装下，但是其实每一层计算增加了。

嗯嗯，好的，谢谢。

**Comment by Caleb66666** [comment]
补充一个，如果使用albert_large及其更大的模型，hidden_size要大于bert_base，如果取的sequence_output使用，后续的计算会更耗时
