### ISSUE TITLE
OOM问题

### ISSUE THREAD

**Issue by DunZhang** [lonePatient/albert_pytorch#14]
您好，非常感谢您提供这个库，但是我在使用的时候遇到一个问题：
我加载albert_base模型，使用8GB的显卡，batch_size设置为64，然后在自己的任务上训练，刚一开始训练的时候，大约占了6.4GB的显存，然后运行了一会突然就报了OOM错误，具体错误信息如下：
```
  File "D:\sentence-transformers-master\albert_pytorch\model\modeling_albert.py", line 285, in forward
    self_outputs = self.self(input_tensor, attention_mask, head_mask)
  File "C:\Users\Zhdun\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\sentence-transformers-master\albert_pytorch\model\modeling_albert.py", line 219, in forward
    context_layer = context_layer.permute(0, 2, 1, 3).contiguous()
RuntimeError: CUDA out of memory. Tried to allocate 26.00 MiB (GPU 0; 8.00 GiB total capacity; 5.84 GiB already allocated; 4.97 MiB free; 415.84 MiB cached)
```
我搞不懂为啥要训练一会才会报这个错误，我不知道是代码存在显存泄露问题，还是自己的代码存在问题，但是我自己的代码很简单，就albert后接了一个孪生网络，我把albert换成bert就没有这种训练一会才会出现OOM的问题。

**Comment by lonePatient** [comment]
@DunZhang 你好，估计是collecate_fn造成的，且你的数据长度是不等长的，我在dataset好像加入了自定义的collecate_fn，主要是为了解决batch的动态padding问题，当出现max_seq_length时候，你的显存无法装下batch_size为64的数据，因为训练过程中显存也是动态变化的。你降低你的batch_size看看 ，或者去掉collecate_fn

**Comment by DunZhang** [comment]
对的，就是你说的问题，非常感谢，如果模型遇到了一个batch的数据比较长就会出现这个问题
