### ISSUE TITLE
转换模型就段错误了~~

### ISSUE THREAD

**Issue by Zawo1995** [lonePatient/albert_pytorch#17]
你好，非常感谢大佬分享的pytorch版本的albert。
我在https://tfhub.dev/google/albert_base/2  上下载了个tf模型，想用它来试试一些下游任务来着，可第一步就卡着了。
我是用windows的git跑的，pytorch是1.2 tf是1.14
不知道是不是模型的参数的原因，希望大佬帮个忙~~
![TIM图片20191104115548](https://user-images.githubusercontent.com/48239524/68098867-366e7b00-fefa-11e9-9493-347eb9965887.png)

**Comment by lonePatient** [comment]
@Zawo1995 你好，window下我没有试过，从你的日志来看，出错是在tf加载变量时候，你在仔细看看，晚点，我把转换好的权重放到云上。

**Comment by lonePatient** [comment]
@Zawo1995 我上传我转换好的pytorch版本模型到谷歌盘，你可以直接下载
