### ISSUE TITLE
我在转换pytorch模型的时候 convert_albert_tf_checkpoint_to_pytorch.py 文件出现问题

### ISSUE THREAD

**Issue by Benjamin-zhangjb** [lonePatient/albert_pytorch#2]
![image](https://user-images.githubusercontent.com/37786414/66364820-891d4b80-e9bd-11e9-9945-4ee18dc35633.png)
请大佬帮忙看下！ 谢谢大佬

**Comment by lonePatient** [comment]
@Benjamin-zhangjb 这个问题我也没遇到过，但是建议你可以吧python版本升级下吧，python3.5我记得使用过程中，问题比较多，我使用的python3.7版本。

**Comment by Benjamin-zhangjb** [comment]
> @ Benjamin-zhangjb这个问题我也没遇到过，但是建议你可以吧python版本升级下吧，python3.5我记得使用过程中，问题比较多，我使用的python3.7版本。

**Comment by Benjamin-zhangjb** [comment]
好的 我升级下试试

**Comment by Benjamin-zhangjb** [comment]
我升级了 一样的错误，麻烦确认下pytorch的版本

**Comment by lonePatient** [comment]
pytorch应该是1.0.0
