### ISSUE TITLE
请教下share_type和embedding_size的选择上有什么建议吗

### ISSUE THREAD

**Issue by BaeSeulki** [lonePatient/albert_pytorch#23]
比如默认all共享和none共享，以及768和128在精度上的差距多大呢，训练速度差距多大呢

**Comment by lonePatient** [comment]
@BaeSeulki 这一块 你看下albert论文 里面做了很相似的实验，需要根据你自己的需求进行训练albert，我在实际应用过程中更多的是拿pretrain模型来对自己的数据集进行语言模型微调
