### ISSUE TITLE
share_type选用attention时 转化出错

### ISSUE THREAD

**Issue by Reveyer** [lonePatient/albert_pytorch#3]
<img width="966" alt="屏幕快照 2019-10-08 下午6 36 21" src="https://user-images.githubusercontent.com/39128351/66389507-22b71e00-e9fb-11e9-862a-06f237233307.png">

**Comment by Reveyer** [comment]
因为cuda版本的原因，我的pytorch版本为1.10
是这个原因么。。？

**Comment by lonePatient** [comment]
@Reveyer 如果你是转化给定的权重的话，share_type必须为all， share_type只是给自己训练的时候可以选择进行实验。

**Comment by Reveyer** [comment]
哦哦，了解了。谢谢啦
