### ISSUE TITLE
请问能否支持一下Lamb optimizer

### ISSUE THREAD

**Issue by lxl910915** [lonePatient/albert_pytorch#30]

**Comment by lxl910915** [comment]
https://github.com/cybertronai/pytorch-lamb/blob/master/pytorch_lamb/lamb.py

**Comment by lonePatient** [comment]
callback里面包含了很多有用的

**Comment by lxl910915** [comment]
> callback里面包含了很多有用的

谢谢，之前没有注意callback这个目录.
