### ISSUE TITLE
albert_tiny_google_zh convert to pytorch

### ISSUE THREAD

**Issue by miangangzhen** [lonePatient/albert_pytorch#32]
I try to convert albert_zh(google version) to pytorch model, but it raise exception:
```shell
Loading TF weight cls/seq_relationship/output_weights/adam_v with shape [2, 312]

Loading TF weight global_step with shape []
Traceback (most recent call last):
  File "convert_albert_tf_checkpoint_to_pytorch.py", line 71, in <module>
    args.pytorch_dump_path)
  File "convert_albert_tf_checkpoint_to_pytorch.py", line 37, in convert_tf_chec
kpoint_to_pytorch
    load_tf_weights_in_albert(model, config, tf_checkpoint_path)
  File "E:\albert_pytorch\albert_chinese_pytorch\model\modeling_albert.py", line
 101, in load_tf_weights_in_albert
    assert pointer.shape == array.shape
AssertionError: (torch.Size([312]), (128,))
```

My steps as follow:
1) Download albert_tiny_zh_google.zip to albert_chinese_pytorch/prev_trained_model
2) Edit albert_config_tiny_g.json, add "ln_type":"postln"
3) run albert_chinese_pytorch/convert_albert_tf_checkpoint_to_pytorch.py

**Comment by lonePatient** [comment]
***** 2019-11-05：新增google版albert_tiny albert_small *****

转换方式：

将English目录中下albert_pytorch/albert_english_pytorch/model/modeling_albert.py 直接替换掉中文版目录下albert_pytorch/albert_chinese_pytorch/model/modeling_albert.py

注释modeling_albert.py中第50行，即：

    #tf_path = tf_path + "/variables/variables"
按照原来版本模式就可以直接转换

**Comment by miangangzhen** [comment]
Thanks you, it works!!!
