### ISSUE TITLE
[Question] 为什么在中文版本使用bert标准分词，英文版本使用sentencepiece分词啊？

### ISSUE THREAD

**Issue by sakuranew** [lonePatient/albert_pytorch#33]
比较好奇这两个之间的效果差别

**Comment by mmy12580** [comment]
其实问题的区别在于什么时候情况下使用wordpiece tokenizer (bert)以及什么时候使用sentencepiece。wordpiece tokenizer的主要方式是Byte Pair Encode，大意是将文本分成字符，然后在词的范围内统计字符对出现的次数，比如词=中文，字符对是(中，文)。而sentencepiece是相对于句子中找到短句中的短语组合，比如“南京大桥”这样的相对长的词语，而不是分解成 “南京/大桥”。对于实际问题，可以考虑哪种更适用于你的情况，比如你的数据如果是法律数据的话，很多时候会出现特有的词语，"民事诉讼法”， “最高人民法院”，这种sentencepiece一般会好使一点。对于英文也是差不多。

**Comment by sakuranew** [comment]
谢谢，不过想用预训练的话也就只能按照当前分词来了

**Comment by mmy12580** [comment]
中文里“字符"已经很够用了，做NER, lexicon analysis,都不错的。百度的LAC，是根据字符为单位的双层的GRU结构模型做的。word segmentation在中文里反而会生成歧义，而在英文里相对会好很多。
