### ISSUE TITLE
与当前huggingface/transformers的代码不兼容

### ISSUE THREAD

**Issue by illcat** [lonePatient/albert_pytorch#35]
貌似只能用你们的pytorch代码，可移植性太差了。

**Comment by lonePatient** [comment]
@illcat huggingface更新太频繁了，及时替换也不是好事，有时候有很多bug，个人建议还是把一个稳定的版本download下来使用，另外在modeling_albert模型，大家实现的方式不一样。你可以手动的修改

**Comment by illcat** [comment]
@lonePatient 我是基于huggingface开发的，看到你们的预训练模型想试一试，结果发现Model文件差距还是挺大的，只能之后再说了。

**Comment by p208p2002** [comment]
原本從 transformers import 的 config, model class
改由作者提供的modeling_albert.py去import config, model class
可相容目前最新transformers  2.3.0
