### ISSUE TITLE
tensorflow到pytorch版本模型转换错误

### ISSUE THREAD

**Issue by Zessay** [lonePatient/albert_pytorch#37]
你好，请问这个错误是tensorflow版本的问题吗？当转换albert-v2版本和brightmart release的albert-base-36k这几个模型会出现这个错误，其他版本转换没问题。

`tensorflow.python.framework.errors_impl.NotFoundError: /cns/yo-d/home/deep-language-generation/albert/exported_models/v_zh/albert_base; No such file or directory`

**Comment by lonePatient** [comment]
@Zessay 你转换的运行命令发下看看，另外你注意下模型路径以及模型文件是否对应

**Comment by Zessay** [comment]
你好，下面是转换的命令行指令，其他版本模型用这个转换都没问题。
![MS)RGD%W0LGI$DV7N72P@B3](https://user-images.githubusercontent.com/39905704/72075346-86205700-332e-11ea-8222-9046b980d9de.png)

**Comment by lonePatient** [comment]
@Zessay 你这个时原始模型的checkpoint文件内容错误，你参考其他模型中的checkpoint内容修改下吧

**Comment by Zessay** [comment]
按照您的建议，修改checkpoint中路径值，可以解决问题。
改动前：
![YZV5 DWIHWFXIQK`KTF_O91](https://user-images.githubusercontent.com/39905704/72119923-1ee7be80-3391-11ea-9d9f-c52cd4a615d2.png)
改动后：
![(6GJOGWF{X6OU$P2WJ1IA~C](https://user-images.githubusercontent.com/39905704/72119936-3161f800-3391-11ea-954a-f3e37a0e4614.png)
