### ISSUE TITLE
Couldn't find 'checkpoint' file or checkpoints in given directory

### ISSUE THREAD

**Issue by jiangjiaqi6** [lonePatient/albert_pytorch#38]
I download the albert_base_v2，but 'checkpoint' file or checkpoints are not  in it,how to solve the problem？

**Comment by lonePatient** [comment]
@jiangjiaqi6 hi，you can add 'checkpoint' file in model dir , For example：
```shell
vim checkpoint
```
add：

```text
model_checkpoint_path: "./model.ckpt-best"
all_model_checkpoint_paths: "./model.ckpt-best"
```

**Comment by jiangjiaqi6** [comment]
I follow your suggestion,vim checkpoint in the model dir,then  command：
python convert_albert_tf_checkpoint_to_pytorch.py    \
 --tf_checkpoint_path=./model  \   
 --bert_config_file=./prev_trained_model/albert_base_v2/config.json     \ --pytorch_dump_path=./prev_trained_model/albert_base_v2/pytorch_model.bin
,but  result is that ：
ValueError: Couldn't find 'checkpoint' file or checkpoints in given directory /home/weifeng/Desktop/albert_pytorch/model
I need your help.

**Comment by lonePatient** [comment]
@jiangjiaqi6 hi, I successfully test the albert_base_v2

file structure of the model：
```text
drwxr-xr-x 2 root root      280 2月   1 20:45 ./
drwxr-xr-x 3 root root       55 2月   1 20:43 ../
-rw-r--r-- 1 root root   760289 2月   1 20:43 30k-clean.model
-rw-r--r-- 1 root root   548994 2月   1 20:43 30k-clean.vocab
-rw-r--r-- 1 root root      480 2月   1 20:43 albert_config.json
-rw-r--r-- 1 root root       91 2月   1 20:43 checkpoint
-rw-r--r-- 1 root root      480 2月   1 20:44 config.json
-rw-r--r-- 1 root root 47255248 2月   1 20:44 model.ckpt-best.data-00000-of-00001
-rw-r--r-- 1 root root     1579 2月   1 20:43 model.ckpt-best.index
-rw-r--r-- 1 root root   809968 2月   1 20:43 model.ckpt-best.meta
-rw-r--r-- 1 root root 47263421 2月   1 20:45 pytorch_model.bin
```
content of the checkpoint file
```text
model_checkpoint_path: "./model.ckpt-best"
all_model_checkpoint_paths: "./model.ckpt-best"
```

and run this cmd:
```python
python convert_albert_tf_checkpoint_to_pytorch.py \
    --tf_checkpoint_path=./prev_trained_model/albert_base \
    --bert_config_file=./prev_trained_model/albert_base/config.json \
    --pytorch_dump_path=./prev_trained_model/albert_base/pytorch_model.bin
```

**Comment by RainFZY** [comment]
@lonePatient Sorry, I have the same problem. In your file structure of the model, how can I get these three files: model.ckpt-best.data-00000-of-00001, model.ckpt-best.index, model.ckpt-best.meta? I don't have them in my file structure.

**Comment by lonePatient** [comment]
@RainFZY in https://github.com/google-research/ALBERT provided by google 。

download model tar file

**Comment by jiangjiaqi6** [comment]
The first problem was solved.I want to generate data,then i run the command:
python prepare_lm_data_ngram.py     --data_dir=dataset/ 
--vocab_path=./prev_trained_model/albert_base_v2/30k-clean.vocab 
--output_dir=outputs/     
--data_name=albert     
--max_ngram=3     
--do_data 
error occurs:FileNotFoundError: [Errno 2] No such file or directory: 'dataset/corpus'
or can you provide a way for me to get data which could be trained by the model.

**Comment by jiangjiaqi6** [comment]
Thank you, the first problem was solved,then I wan to fine tuning albert model, I run 
sh run_classifier_sst2.sh,I found that dataset dir don't have sst-2,error shows:
[Errno 2] No such file or directory: '/home/weifeng/Desktop/albert_pytorch/dataset/sst-2/train.tsv'
how can i get train.tsv? or how to solve this problem?

**Comment by lonePatient** [comment]
@jiangjiaqi6 Hi, Before running anyone of these GLUE tasks you should download the [GLUE data](https://gluebenchmark.com/tasks) by running [this script](https://gist.github.com/W4ngatang/60c2bdb54d156a41194446737ce03e2e) and unpack it to some directory $DATA_DIR.
