### ISSUE TITLE
AlbertForNextSentencePrediction

### ISSUE THREAD

**Issue by yzgdjqwh** [lonePatient/albert_pytorch#41]
modeling_albert.py中AlbertForNextSentencePrediction类的示例如下：
Examples::
        tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
        model = BertForNextSentencePrediction.from_pretrained('bert-base-uncased')
        input_ids = torch.tensor(tokenizer.encode("Hello, my dog is cute")).unsqueeze(0)  
        outputs = model(input_ids)
        seq_relationship_scores = outputs[0]
似乎不对，能提供一个正确的范例吗？请帮助

**Comment by lonePatient** [comment]
@yzgdjqwh 参考下`run_classifier.py`里面的调用方法吧，class里面没有参考价值，因为主要是从transformers中的bert模型文件直接移植过来修改的，模型没有保存服务路径，所以只能加载本地模型，而且tokenizer没有encode模块，（我主要还是在使用老版本的transformers模块)

**Comment by lonePatient** [comment]
@yzgdjqwh 比较简单的一个方法时，你下载transformers包到本地，然后把里面的albert模型文件修改下就可以了，或者可以直接transformers里面自带的

**Comment by yzgdjqwh** [comment]
好的，谢谢
