### ISSUE TITLE
How can I do when there is only 1 sentence in a document?

### ISSUE THREAD

**Issue by SCNUJackyChen** [lonePatient/albert_pytorch#43]
in "prepare_lm_data_ngram.py", line 98 
` assert len(tokens_b) >= 1`
it is supposed that 'tokens_b' should not be empty

However, I wonder how can I do when I wanna to deal with document with only one sentence?

**Comment by lonePatient** [comment]
@SCNUJackyChen 去掉SOP任务就可以了，你可以参考达观比赛数据，该数据只有一个句子且很短，代码:https://github.com/lonePatient/daguan_2019_rank9

**Comment by SCNUJackyChen** [comment]
@lonePatient 多谢大神指点
