### ISSUE TITLE
关于继续pretrain的问题

### ISSUE THREAD

**Issue by SCNUJackyChen** [lonePatient/albert_pytorch#44]
你好，我用`run_pretrain.py`训练并保存checkpoint后，把`model_path，config，vocab`分别换成checkpoint的对应的文件，然后重新运行。理论上应该是基于checkpoint继续训练，但是从eval的acc和loss上看，貌似模型没有保存好，或者模型不是保存时刻的模型（重新加载后的起始loss很大，且mask acc和sop acc均很低）。
请问这是我的做法有误吗？

**Comment by lonePatient** [comment]
@SCNUJackyChen  问题应该出现在tie_weight这里，你把这个去掉，然后重新加载chenkpoint看看，差距还大吗？另外建议加个optimizer的save，先 试试去掉tie_weight，

**Comment by SCNUJackyChen** [comment]
@lonePatient 按照你的建议我去掉了`modeling_utils.py` line 374
`if hasattr(model, 'tie_weights'):`
    ` model.tie_weights()  # make sure word embedding weights are still tied`

重新运行后还是差距很大，和之前一样

**Comment by lonePatient** [comment]
@SCNUJackyChen 代码或者数据方便公开吗？我看看，之前我记得个人实验过偏差不是很大的，或者运行方式发我看看 （代码或者数据（如果数据方便公开的话）可以打个包发我邮箱吧 ！我调试下看看

**Comment by SCNUJackyChen** [comment]
@lonePatient 已发。十分感谢！

**Comment by lonePatient** [comment]
@我实验结果已经邮件发给你，实验出来是没有问题，tie_weight这个之前已经改了，另外在加载checkpoint继续训练时，lr建议降低一个级别
