### ISSUE TITLE
“pooled_output = self.dropout(pooled_output+0.1)” is confusing

### ISSUE THREAD

**Issue by matricer** [lonePatient/albert_pytorch#45]
the code in AlbertForSequenceClassification is confusing
![image](https://user-images.githubusercontent.com/16053879/76401962-ae274780-63bd-11ea-83c5-b651bdc8177e.png)
why use "pooled_output = self.dropout(pooled_output+0.1)" rather than "pooled_output = self.dropout(pooled_output)"

**Comment by lonePatient** [comment]
@matricer 我记得config里面的drop为0.0，试验中0.1的dropout相对会好点，其实这块参数可以根据任务调，有时0.3可以达到最好。
