### ISSUE TITLE
not initialized from pretrained model: ['bert.albert.embeddings.word_embeddings.weight', 'bert.albert.embeddings.position_embeddings.weight', 'bert.albert.embeddings.token_type_embeddings.weight',

### ISSUE THREAD

**Issue by yc0815024** [lonePatient/albert_pytorch#49]
你好，我下载了您链接下的albert_large，加载模型的时候出现了这个问题：ot initialized from pretrained model: ['bert.albert.embeddings.word_embeddings.weight', 'bert.albert.embeddings.position_embeddings.weight', 'bert.albert.embeddings.token_type_embeddings.weight', 'bert.albert.embeddings.LayerNorm.weight', 'bert.albert.embeddings.LayerNorm.bias', 'bert.albert.encoder.embedding_hidden_mapping_in.weight', 'bert.albert.encoder.embedding_hidden_mapping_in.bias', 'bert.albert.encoder.transformer.group.0.inner_group.0.attention.self.query.weight', 'bert.albert.encoder.transformer.group.0.inner_group.0.attention.self.query.bias', 'bert.albert.encoder.transformer.group.0。
是我加载的模型不对吗？

**Comment by lonePatient** [comment]
@yc0815024 把你的命令发出看看

**Comment by yc0815024** [comment]
命令如下：
export CUDA_VISIBLE_DEVICES=0
python run_s_v2.py \
--model_name_or_path ./prev_trained_model/albert_large \
--gradient_accumulation_steps 2 \
--do_train \
--do_eval \
--data_dir ./data \
--test_dir ./data \
--vocab_file ./prev_trained_model/albert_large/vocab.txt \
--output_dir ./output/ \
--max_seq_length 360 \
--max_question_length 50 \
--eval_steps 800 \
--per_gpu_train_batch_size 8 \
--per_gpu_eval_batch_size 10 \
--learning_rate 2e-5 \
--train_steps 64000

模型目录如下：
config.json  pytorch_model.bin  vocab.txt

**Comment by yc0815024** [comment]
> @yc0815024 把你的命令发出看看
命令如下：
export CUDA_VISIBLE_DEVICES=0
python run_s_v2.py
--model_name_or_path ./prev_trained_model/albert_large
--gradient_accumulation_steps 2
--do_train
--do_eval
--data_dir ./data
--test_dir ./data
--vocab_file ./prev_trained_model/albert_large/vocab.txt
--output_dir ./output/
--max_seq_length 360
--max_question_length 50
--eval_steps 800
--per_gpu_train_batch_size 8
--per_gpu_eval_batch_size 10
--learning_rate 2e-5
--train_steps 64000

模型目录如下：
config.json pytorch_model.bin vocab.txt

**Comment by lonePatient** [comment]
@yc0815024 模型权重文件跟模型文件对应上了吗，里面与modeling_albert.py和modeling_albert_bright.py两种  你看下是不是加载错了，看你的命令好像也是对的 。

**Comment by yc0815024** [comment]
感谢您的回复。我代码里面继承类的时候把self.bert写成self.albert了，问题已经解决了。
