### ISSUE TITLE
选择share_type为attention时convert_albert_tf_checkpoint_to_pytorch.py 文件出现问题

### ISSUE THREAD

**Issue by yyaaa1** [lonePatient/albert_pytorch#6]
<img width="466" alt="Screen Shot 2019-10-09 at 7 40 56 PM" src="https://user-images.githubusercontent.com/44675597/66528264-4054b800-eacd-11e9-9ce9-17911a1eea92.png">
share_type除了在all的情况下程序可以成功运行，另外三种情况都会报类似的错误。希望大神帮忙解决！ 感谢

**Comment by lonePatient** [comment]
@yyaaa1 如果你是转化给定的权重的话，share_type必须为all， share_type只是给自己训练的时候可以选择进行实验。

**Comment by yyaaa1** [comment]
> @yyaaa1 如果你是转化给定的权重的话，share_type必须为all， share_type只是给自己训练的时候可以选择进行实验。
懂了！感谢
