### ISSUE TITLE
基于albert模型继续在自己的数据集上pretraining albert的问题 

### ISSUE THREAD

**Issue by liuxiaohao-xn** [lonePatient/albert_pytorch#60]
您好，很感谢你分享代码，我在训练的时候遇到如下问题，以下是问题的场景：
        我想基于albert预训练好的权重，在自己的数据集上继续pretraining albert模型，如参数设置args.model_path=./prev_trained_model/albert_base_zh， 但是在运行过程中报错了，我查看代码发现 if args.model_path != None时，会加载args.model_path下的optimizer.bin(梯度值?)文件，但我下载的albert_base_zh文件中只有config.json、pytorch_model.bin、vocab.txt这三个文件，您能解答我的疑惑吗，我该怎么得到optimizer.bin文件，或者我的思路时错误的,万分感谢！！！

**Comment by lhz211** [comment]
您好！请问您解决这个问题了吗，我也遇到了这个问题

**Comment by lhz211** [comment]
哦我明白了，那个没用，不应该在预训练时加载他
