### ISSUE TITLE
A Bug?

### ISSUE THREAD

**Issue by develpoerkk** [lonePatient/albert_pytorch#7]
albert_pytorch/run_classifier.py 第135行，多GPU运行验证时会报错，单GPU运行则不会
eval_loss.update(loss.item(), n=batch[0].size()[0])
loss.item()，会报loss维度不是1，无法转化为一个数。
要不改一下？

**Comment by lonePatient** [comment]
@develpoerkk 多卡是被报错，我当时测试时候直接在单卡上进行的，多卡的 你将loss.mean()，回头我把代码更新下。

**Comment by develpoerkk** [comment]
Ok
